version: '3.8'

services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: maxdrive-backend
    ports: 
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
    restart : unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maxdrive-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    restart : unless-stopped